name: Azure Cost CLI Workflow

on:
  workflow_dispatch:
    inputs:
      az-subscription-id:
        description: 'Azure Subscription ID'
        required: true
jobs:
  run-azure-cost-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install mermaid-cli
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Install Azure Cost CLI
        run: dotnet tool install -g azure-cost-cli --no-cache

      - name: Run Azure Cost CLI
        run: azure-cost -o markdown --subscription ${{ github.event.inputs.az-subscription-id }} > cost.md

      - name: Post results to GITHUB SUMMARY
        run: cat cost.md >> $GITHUB_STEP_SUMMARY

      - name: Transform a markdown file with mermaid diagrams # find the mermaid diagrams, create SVG files from them and refer to those in the markdown output
        run: mdc -i cost.md -o cost-svg.md

      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: cost-svg.md
          output: cost-svg.html
          github-corners: https://github.com/jaywcjlove/markdown-to-html-cli
          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🌐</text></svg>

      - name: Post results to storageaccount
        run: az storage blob upload -f cost-svg.html -c '$web' --account-name ${{ vars.AZURE_ST_ACCOUNT_NAME }} -n "cost-svg-${{ github.event.inputs.az-subscription-id }}-$(date +"%d-%m-%Y").html"
