name: Azure Cost CLI + Pandoc Workflow

on:
  workflow_dispatch:
    inputs:
      az-subscription-id:
        description: 'Azure Subscription ID'
        required: true
jobs:
  run-azure-cost-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure Cost CLI
        run: dotnet tool install -g azure-cost-cli --no-cache

      - name: Run Azure Cost CLI
        run: azure-cost -o markdown --subscription ${{ github.event.inputs.az-subscription-id }} > cost.md

      - name: Post results to GITHUB SUMMARY
        run: cat cost.md >> $GITHUB_STEP_SUMMARY

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc
      
      - name: Install mermaid-filter for pandoc
        run: npm install --global mermaid-filter
      
      - name: Install mermaid-filter for pandoc
        run: pandoc -t html -F mermaid-filter -o something.html cost.md

      - name: Post results to storageaccount
        run: az storage blob upload-batch --account-name ${{ vars.AZURE_ST_ACCOUNT_NAME }} --destination '$web' --destination-path "pandoc-1-${{ github.event.inputs.az-subscription-id }}-$(date +"%d-%m-%Y")" --source '.'
        
